# Generated by Django 4.2.25 on 2025-11-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicformfields',
            options={'ordering': ['field_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='employeedata',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='dynamicformfields',
            name='field_order',
            field=models.IntegerField(),
        ),
    ]
