# Generated by Django 4.2.25 on 2025-11-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_dynamicformfields_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='employee_id',
            field=models.CharField(max_length=15),
        ),
    ]
